### ISSUE TITLE
PolicyTypeHash validation requires size check

### ISSUE THREAD

**Issue by Alrighttt** [SiaFoundation/core#206]
https://github.com/SiaFoundation/core/blob/0f61e58ab7ea932da7e9f710c592d595406356c6/types/policy.go#L155

An additional check on the size of the preimage must be performed in this case. 

I recommend checking that the preimage is 32 bytes. Technically you can support preimages less than 32 bytes, but there is no practical use for this. 

See:
https://gist.github.com/markblundeberg/7a932c98179de2190049f5823907c016

**Comment by Alrighttt** [comment]
Exact size check of `length(preimage) == 32` is recommended, but if it will support a variable size, the size must be configurable. 

ie,
```
type PolicyTypeHash struct {
	Len  uint16
	Hash Hash256
}
```

**Comment by lukechampine** [comment]
I'm ok hardcoding it to 32 bytes. There's certainly no need to go *longer* than that, and if you want to go shorter, you can zero-pad.

**Comment by lukechampine** [comment]
Is 32 the recommended length because, in practice, these preimages are always 32-byte randomly-generated secrets? (Is there *any* atomic swap protocol that uses a different length secret?)

I suppose there's little point in making in variable-size, since you can always hash the preimage *twice* -- that is, you can always hash a preimage to get an exactly-32-byte preimage for use with `PolicyTypeHash`.

**Comment by Alrighttt** [comment]
> I suppose there's little point in making in variable-size, since you can always hash the preimage _twice_ -- that is, you can always hash a preimage to get an exactly-32-byte preimage for use with `PolicyTypeHash`.

Yes, exactly. Thanks for the prompt fix.
